language: python
dist: xenial
cache: pip
python: '3.7'  # "Default" Python version

install:
- pip install --upgrade codecov tox
before_script:
- |
  if [[ -z $TOXENV ]]; then
    export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
- echo $TOXENV
script:
- tox -e $TOXENV
after_success:
- codecov

matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO=master

  include:
  - env: TOXENV=qa
  - env: TOXENV=docs

  - env: DJANGO=21

  # Test the latest Django LTS release against all supported Pythons: 3.5, 3.6, 3.7
  - env: DJANGO=22
    python: '3.5'
  - env: DJANGO=22
    python: '3.6'
  - env: DJANGO=22
    python: '3.7'

  - env: DJANGO=master

  - stage: PyPI release  # will run after the default "test" stage succeeds
    script: echo "Deploying to PyPI ..."  # override regular test script; "skip" should also work
    if: tag IS present
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: codingjoe
      password:
        secure: jJyadofJm7F1Qco+EDCyN/aMZaYSbfQ0GAE02Bx7I499MkjPYvv38X2btg+PjdW3rzGD0d/kq24lfWLkgKncyQ/YMgLQ7H/GuCCHHYbKUklxllaoFXActBjstmKOvXyWWC5oEb+YEJ4HTwgkvS6wkp69B7C1d4BAOqGs5IKnCSo=
      on:
        tags: true
        repo: KristianOellegaard/django-health-check
        branch: master
